#!/usr/bin/env python3
"""Generate local SVG assets used by the GitHub profile README."""

from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Any, Dict, List

ROOT = Path(__file__).resolve().parents[2]
CONFIG_PATH = ROOT / "profile.config.json"
ASSETS_DIR = ROOT / "assets"


def load_config() -> Dict[str, Any]:
    return json.loads(CONFIG_PATH.read_text(encoding="utf-8"))


def esc(value: Any) -> str:
    return html.escape(str(value or ""), quote=True)


def clamp(value: Any, low: int = 0, high: int = 100) -> int:
    try:
        number = int(float(value))
    except Exception:
        number = 0
    return max(low, min(high, number))


def svg_wrapper(width: int, height: int, content: str) -> str:
    return f'''<svg width="{width}" height="{height}" viewBox="0 0 {width} {height}" fill="none" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Generated GitHub profile asset">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#020617"/>
      <stop offset="45%" stop-color="#0f172a"/>
      <stop offset="100%" stop-color="#082f49"/>
    </linearGradient>
    <linearGradient id="accent" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0%" stop-color="#38bdf8"/>
      <stop offset="60%" stop-color="#22c55e"/>
      <stop offset="100%" stop-color="#f97316"/>
    </linearGradient>
    <filter id="shadow" x="-20%" y="-20%" width="140%" height="140%">
      <feDropShadow dx="0" dy="8" stdDeviation="12" flood-color="#000000" flood-opacity="0.35"/>
    </filter>
  </defs>
  <rect width="{width}" height="{height}" rx="26" fill="url(#bg)"/>
  <circle cx="{width - 70}" cy="65" r="120" fill="#38bdf8" opacity="0.08"/>
  <circle cx="80" cy="{height - 45}" r="150" fill="#22c55e" opacity="0.07"/>
{content}
</svg>
'''


def generate_engineering_matrix(config: Dict[str, Any]) -> str:
    domains: List[Dict[str, Any]] = config.get("engineering_domains") or []
    width = 1100
    row_h = 54
    height = 132 + row_h * max(len(domains), 1)
    items = [
        '  <text x="44" y="58" fill="#e2e8f0" font-family="Inter, Segoe UI, Arial" font-size="30" font-weight="800">Engineering Signal Matrix</text>',
        '  <text x="44" y="88" fill="#94a3b8" font-family="Inter, Segoe UI, Arial" font-size="15">Config-driven skill/evidence board generated by GitHub Actions</text>',
    ]
    y = 126
    for item in domains:
        domain = esc(item.get("domain", "Engineering"))
        level = clamp(item.get("level", 0))
        evidence = esc(item.get("evidence", "Evidence configured in profile.config.json"))
        bar_width = int(360 * level / 100)
        items.append(f'  <rect x="44" y="{y - 30}" width="1012" height="42" rx="14" fill="#0f172a" opacity="0.82" filter="url(#shadow)"/>')
        items.append(f'  <text x="68" y="{y - 4}" fill="#f8fafc" font-family="Inter, Segoe UI, Arial" font-size="16" font-weight="700">{domain}</text>')
        items.append(f'  <rect x="285" y="{y - 18}" width="360" height="12" rx="6" fill="#1e293b"/>')
        items.append(f'  <rect x="285" y="{y - 18}" width="{bar_width}" height="12" rx="6" fill="url(#accent)"/>')
        items.append(f'  <text x="664" y="{y - 5}" fill="#38bdf8" font-family="JetBrains Mono, Consolas, monospace" font-size="15" font-weight="700">{level}%</text>')
        items.append(f'  <text x="735" y="{y - 5}" fill="#cbd5e1" font-family="Inter, Segoe UI, Arial" font-size="13">{evidence}</text>')
        y += row_h
    return svg_wrapper(width, height, "\n".join(items))


def generate_automation_workflow(config: Dict[str, Any]) -> str:
    width = 1100
    height = 360
    steps = [
        ("Trigger", "schedule / push / dispatch"),
        ("Quality Gate", "JSON + tests + markers"),
        ("Assets", "SVG generation"),
        ("GitHub API", "repos + languages + events"),
        ("README", "dynamic block rewrite"),
        ("Commit", "bot pushes update"),
    ]
    items = [
        '  <text x="44" y="58" fill="#e2e8f0" font-family="Inter, Segoe UI, Arial" font-size="30" font-weight="800">Profile Automation Pipeline</text>',
        f'  <text x="44" y="88" fill="#94a3b8" font-family="Inter, Segoe UI, Arial" font-size="15">{len(config.get("profile_workflows") or [])} workflows coordinate validation, generation, maintenance, and release packaging</text>',
    ]
    x = 48
    y = 148
    card_w = 150
    gap = 28
    for index, (title, subtitle) in enumerate(steps):
        items.append(f'  <rect x="{x}" y="{y}" width="{card_w}" height="116" rx="20" fill="#0f172a" opacity="0.9" filter="url(#shadow)"/>')
        items.append(f'  <circle cx="{x + 30}" cy="{y + 30}" r="15" fill="#38bdf8" opacity="0.18"/>')
        items.append(f'  <text x="{x + 24}" y="{y + 36}" fill="#38bdf8" font-family="JetBrains Mono, Consolas, monospace" font-size="16" font-weight="800">{index + 1}</text>')
        items.append(f'  <text x="{x + 20}" y="{y + 70}" fill="#f8fafc" font-family="Inter, Segoe UI, Arial" font-size="17" font-weight="800">{esc(title)}</text>')
        items.append(f'  <text x="{x + 20}" y="{y + 94}" fill="#94a3b8" font-family="Inter, Segoe UI, Arial" font-size="12">{esc(subtitle)}</text>')
        if index < len(steps) - 1:
            ax = x + card_w + 6
            items.append(f'  <path d="M {ax} {y + 58} H {ax + gap - 14}" stroke="#38bdf8" stroke-width="3" stroke-linecap="round" opacity="0.72"/>')
            items.append(f'  <path d="M {ax + gap - 20} {y + 50} L {ax + gap - 10} {y + 58} L {ax + gap - 20} {y + 66}" stroke="#38bdf8" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" opacity="0.72"/>')
        x += card_w + gap
    items.append('  <text x="44" y="318" fill="#cbd5e1" font-family="Inter, Segoe UI, Arial" font-size="14">Result: a profile README that behaves like a small production system — tested, scheduled, observable, and self-updating.</text>')
    return svg_wrapper(width, height, "\n".join(items))


def generate_profile_layers(config: Dict[str, Any]) -> str:
    width = 1100
    height = 300
    sections = config.get("profile_sections") or []
    items = [
        '  <text x="44" y="58" fill="#e2e8f0" font-family="Inter, Segoe UI, Arial" font-size="30" font-weight="800">README Module System</text>',
        '  <text x="44" y="88" fill="#94a3b8" font-family="Inter, Segoe UI, Arial" font-size="15">Each module is independently regenerated through comment markers</text>',
    ]
    x = 44
    y = 126
    for i, section in enumerate(sections[:10]):
        w = 196 if i % 3 == 0 else 176
        if x + w > width - 44:
            x = 44
            y += 62
        items.append(f'  <rect x="{x}" y="{y}" width="{w}" height="42" rx="14" fill="#0f172a" opacity="0.9"/>')
        items.append(f'  <text x="{x + 16}" y="{y + 27}" fill="#e2e8f0" font-family="Inter, Segoe UI, Arial" font-size="14" font-weight="700">{esc(section)}</text>')
        x += w + 16
    return svg_wrapper(width, height, "\n".join(items))


def main() -> int:
    config = load_config()
    ASSETS_DIR.mkdir(exist_ok=True)
    outputs = {
        "engineering-matrix.svg": generate_engineering_matrix(config),
        "automation-workflow.svg": generate_automation_workflow(config),
        "profile-layers.svg": generate_profile_layers(config),
    }
    for filename, content in outputs.items():
        (ASSETS_DIR / filename).write_text(content, encoding="utf-8")
        print(f"generated assets/{filename}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
